---
version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_patterns:
      - spec/
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
  reek:
    enabled: true
exclude_patterns:
- bin/
- config/
- public/
- tmp/
- db/
