language: ruby
cache: bundler
bundler_args: --without guard --deployment
services:
  - postgresql
rvm:
  - 2.5.1
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rails db:migrate
  - bundle exec rails db:seed
env:
  RAILS_ENV=test

script: bundle exec rspec
