version: '2'
services:
  postgres:
    image: postgres:10-alpine
    environment:
      - PGDATA=/postgresql
      - PG_PASSWORD=qwert
    ports:
      - 5432:5432
    volumes:
      - ./tmp/data/postgresql:/postgresql

  web:
    build: .
    command: bundle exec rails server
    environment:
      - RAILS_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwert
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/app
