default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: qwert
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TheHoneydew_development

test:
  <<: *default
  database: travis_ci_test

production:
  url: <%= ENV['DATABASE_URL'] %>
