default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TheHoneydew_development
  host: localhost
  username: qwert
  password: qwert

test:
  <<: *default
  database: TheHoneydew_test


  production:
    url: <%= ENV['DATABASE_URL'] %>
