default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TheHoneydew_development
  host: postgres
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

test:
  <<: *default
  database: travis_ci_test

production:
  url: <%= ENV['DATABASE_URL'] %>
