# frozen_string_literal: true

User.create(login: 'keva', password: 'KeV@1SLifE', is_admin: true)
User.create(login: 'user', password: 'Mu$t@Ng_V0')

Inspector.create(last_name: 'Аксиненко', first_name: 'Сергей', middle_name: 'Владимирович', position: 'Председатель комитета - заместитель начальника управления')
Inspector.create(last_name: 'Маляр', first_name: 'Павел', middle_name: 'Иванович', position: 'Председатель комитета')
Inspector.create(last_name: 'Ульянов', first_name: 'Павел', middle_name: 'Владимирович', position: 'Начальник отдела')
Inspector.create(last_name: 'Шабанова', first_name: 'Ольга', middle_name: 'Ивановна', position: 'И.о. начальника отдела')
Inspector.create(last_name: 'Веткин', first_name: 'Сергей', middle_name: 'Алексеевич', position: 'Главный специалист')
Inspector.create(last_name: 'Гуляев', first_name: 'Алексей', middle_name: 'Игоревич', position: 'Консультант')
Inspector.create(last_name: 'Гусева', first_name: 'Ксения', middle_name: 'Анатольевна', position: 'Главный специалист')
Inspector.create(last_name: 'Соболева', first_name: 'Вера', middle_name: 'Анатольевна', position: 'Консультант')
Inspector.create(last_name: 'Бугаева', first_name: 'Татьяна', middle_name: 'Геннадьевна', position: 'Главный специалист')
Inspector.create(last_name: 'Золотухин', first_name: 'Антон', middle_name: 'Игоревич', position: 'Заместитель председателя комитета')
Inspector.create(last_name: 'Семиколенов', first_name: 'Игорь', middle_name: 'Владимирович', position: 'Консультант')
Inspector.create(last_name: 'Сусоев', first_name: 'Владимир', middle_name: 'Михайлович', position: 'Консультант')
Inspector.create(last_name: 'Горев', first_name: 'Дмитрий', middle_name: 'Васильевич', position: 'Главный специалист')
Inspector.create(last_name: 'Панова', first_name: 'Евгения', middle_name: 'Николаевна', position: 'Главный специалист')
Inspector.create(last_name: 'Семин', first_name: 'Станислав', middle_name: 'Олегович', position: 'Консультант')
Inspector.create(last_name: 'Удут-Пантелиади', first_name: 'Ирина', middle_name: 'Викторовна', position: 'Консультант')
Inspector.create(last_name: 'Панова', first_name: 'Татьяна', middle_name: 'Владимировна', position: 'Консультант')
Inspector.create(last_name: 'Пономарева', first_name: 'Алия', middle_name: 'Александровна', position: 'Консультант')
Inspector.create(last_name: 'Панькова', first_name: 'Олеся', middle_name: 'Васильвена', position: 'Консультант')
Inspector.create(last_name: 'Трубина', first_name: 'Полина', middle_name: 'Ивановна', position: 'Консультант')
Inspector.create(last_name: 'Думина', first_name: 'Юлия', middle_name: 'Анатольевна', position: 'Консультант')

Category.create(name: 'эффективность деятельности')
Category.create(name: 'сохранение и использование имущества')
Category.create(name: 'государственные/муниципальные услуги')
Category.create(name: 'контрактная система')
Category.create(name: 'противодействие коррупции')
Category.create(name: 'для обращений :: нецелевое использование бюджетных средств')
Category.create(name: 'для обращений :: оспаривание действий должностных лиц')
Category.create(name: 'другие')

Violation.create(name: 'трудовое законодательство')
Violation.create(name: 'законодательство о государственных и муниципальных услугах')
Violation.create(name: 'законодательство о контрактной системе')
Violation.create(name: 'бюджетное законодательство')
Violation.create(name: 'ведомственное законодательство')
Violation.create(name: 'другие')

ResponseMeasure.create(name: 'расторжение трудовых договоров')
ResponseMeasure.create(name: 'дисциплинарные взыскания')
ResponseMeasure.create(name: 'возвращение денежных средств в бюджет')
ResponseMeasure.create(name: 'административные наказания :: прокуратура')
ResponseMeasure.create(name: 'административные наказания :: ИОГВ')
ResponseMeasure.create(name: 'административные наказания :: контрольный комитет КРУ')
ResponseMeasure.create(name: 'факты не подтвердились')
ResponseMeasure.create(name: 'другие')

DirectionStatus.create(name: 'Для сведения')
DirectionStatus.create(name: 'Для принятия мер реагирования')
DirectionStatus.create(name: 'Для устранения нарушений')

Reason.create(name: 'план работы КК и ОАР')
Reason.create(name: 'поручение ГТО')
Reason.create(name: 'поручение ЗГТО')
Reason.create(name: 'обращение заявителя/организации')
Reason.create(name: 'другое')

Result.create(name: 'снято с контроля')
Result.create(name: 'переведено на внутренний контроль')
